### PR TITLE
Fix get non fungible tokens list

### PR DESCRIPTION
**Pull request by ssd04**
## Reasoning behind the pull request
- Add custom handling for NonFungibleESDT and NonFungibleESDTv2

## Testing procedure
- Standard system test
- Observer and Proxy testing for "/network/esdt/non-fungible-tokens" endpoint - it should list all non fungible tokens

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

### CODE REVIEW

**Review by bogdan-rosianu — DISMISSED** [review]

**Review by miiu96 — DISMISSED** [review]

**Review by BeniaminDrasovean — DISMISSED** [review]
Is it ok to merge this directly into master?

**Comment by ssd04** [comment]
> Is it ok to merge this directly into master?

directed it to master for now, will see exactly where we'll merge it

**Comment by sstanculeanu** [comment]
Run Tests:
mx-chain-simulator-go: main
mx-chain-testing-suite: main

**Review by BeniaminDrasovean — APPROVED** [review]

**Review by AdoAdoAdo — APPROVED** [review]

**Review by andreibancioiu — APPROVED** [review]

**Comment by andreibancioiu** [comment]
System tests passed :heavy_check_mark:

**Comment by sstanculeanu** [comment]
Run Tests:
mx-chain-simulator-go: main
mx-chain-testing-suite: main

**Review by bogdan-rosianu — APPROVED** [review]

**Review by miiu96 — APPROVED** [review]

**Pull request merged**
