### PR TITLE
upgrade wasmer executor version

### PR DESCRIPTION
**Pull request by laurci**
## Reasoning behind the pull request
- 
- 
- 
  
## Proposed changes
- 
- 
- 

## Testing procedure
- 
- 
- 

## Pre-requisites

Based on the [Contributing Guidelines](https://github.com/multiversx/mx-chain-go/blob/master/.github/CONTRIBUTING.md#branches-management) the PR author and the reviewers must check the following requirements are met:
- was the PR targeted to the correct branch?
- if this is a larger feature that probably needs more than one PR, is there a `feat` branch created?
- if this is a `feat` branch merging, do all satellite projects have a proper tag inside `go.mod`?

### CODE REVIEW

**Review by sasurobert — DISMISSED** [review]

**Review by sasurobert — APPROVED** [review]

**Review by andreibancioiu — DISMISSED** [review]
Tested.

**Review by sasurobert — DISMISSED** [review]

**Review by andreibancioiu — COMMENTED** [review]
I'll redo an older test, I'll approve afterwards.

**Review by andreibancioiu — CHANGES_REQUESTED** [review]
Older test failed.

**Review by andreibancioiu — APPROVED** [review]
Final fix would be non-breaking, can follow afterwards.

**Review by andreibancioiu — APPROVED** [review]

**Review by sasurobert — APPROVED** [review]

**Pull request merged**
